### PR TITLE
Remove "something went wrong" channel output.

### PR DESCRIPTION
**Pull request by Kays**
While this could be optimized to only print to a certain "admin" channel or only print once after some period of time, I think prioritizing it to not say this every minute is higher priority in v3 and leave the main fix for v4. This will at least make it tolerable, especially when the bot owner is sleeping or afk and doesn't have to come back to thousand of messages.

### CODE REVIEW

**Comment by BitQuote** [comment]
It shouldn't be sending the message every minute...

**Comment by Kays** [comment]
I haven't figured out the cause of it because it happens so infrequently. Like only twice since I've installed it. But waking up to see this in a channel was not cool. http://i.imgur.com/yaeDt5g.png

**Comment by BitQuote** [comment]
Has this ever happened on the official bot?

**Comment by Kays** [comment]
I haven't ran the official bot much since self-host. Since no one else has reported it, I would say no. But some people in self-host channel have also mentioned it. It's not a big deal to merge this, but may help some people's self-host instance. I'm not sure if it has to do with certain package versioning or not. Something to keep in mind for v4 package.json maybe?

**Pull request closed without merging**
