### PR TITLE
reduced amount of lines in bot.js

### PR DESCRIPTION
**Pull request by deansheather**
this is what your code looks like to me

you're welcome

### CODE REVIEW

**Comment by Oliy1492** [comment]
I THInk ThIs wiLL FIz EvErYtHing 1/1

**Comment by HcgRandon** [comment]
5/7 Shard issue finally fixed 👍

**Comment by deansheather** [comment]
You dont seem to understand how much this affects my ability to live in a peaceful environment, here is an example of the things that have come of the lack of real time traffic information for my route to find cat https://github.com/BitQuote/AwesomeBot/pull/198

**Comment by Ovyerus** [comment]
luks guyd

**Comment by deansheather** [comment]
this is just such an awesome bot, i hope you can add route information to help me find cat

🌵

**Comment by Programmix** [comment]
Please enlighten us by merging this, Ashwin Srinivasan.

**Comment by tinytaco8** [comment]
is this what happens when i don't check github

**Pull request closed without merging**
